@Restaurants.API_HostAddress = https://localhost:7090

GET {{Restaurants.API_HostAddress}}/api/restaurants

###
@id=14
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Ben",
  "Description": "A cozy Italian restaurant offering authentic pizzas, pastas, and a variety of delicious desserts.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "contact@bellaitalia.com",
  "ContactNumber": "+1-800-555-0345",
  "City": "New York",
  "Street": "456 Pasta Lane",
  "PostalCode": "10-010"
}

###


DELETE {{Restaurants.API_HostAddress}}/api/restaurants/7

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json

{
  "Name" : "Sample patch",
  "Description": "This is a sample restaurant description.",
  "HasDelivery" : true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurant/14/dishes
Content-Type: application/json

{
  "Name" : "Ice-Cream Americano",
  "Description" : "Best Ice-cream  in the world!",
  "Price" : 7.99,
  "KiloCalories" : 500
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/14/dishes

###
